version: '3'

services:
  minimarket-front:
    container_name: minimarket-front
    image: minimarket-front:1
    build:
      context: Saas_Virgen_de_Lourdes
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
  
