name: Deploy Minimarket Frontend

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd minimarket_virgen_lourdes_frontend  # Cambia esto al directorio correcto de tu frontend
          docker build -t minimarket-front:latest .

      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 149.50.132.9 >> ~/.ssh/known_hosts || true

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p5118 root@149.50.132.9 << 'EOF'
            cd DeployVirgenLourdesFront/minimarket_frontend_remoto || exit
            git pull origin master
            docker-compose up -d --build
          EOF
